// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPXaltUAEava1o1wwnui9AvAAU-jLqKZE',
    appId: '1:527655586905:android:ef671fd547c8f76b787548',
    messagingSenderId: '527655586905',
    projectId: 'rover-taxi',
    databaseURL: 'https://rover-taxi.firebaseio.com',
    storageBucket: 'rover-taxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWroN3Zw1NNRVoE48RjMHNTkQMC0pLOvE',
    appId: '1:527655586905:ios:96f0433fc1015570787548',
    messagingSenderId: '527655586905',
    projectId: 'rover-taxi',
    databaseURL: 'https://rover-taxi.firebaseio.com',
    storageBucket: 'rover-taxi.appspot.com',
    androidClientId: '527655586905-1q41t7alk6g9s14tdu7u6k7ha0i0tpr8.apps.googleusercontent.com',
    iosBundleId: 'com.app.rovertaxiDriver',
  );
}
